#!/bin/bash

#
# setup environment
set -xe
source /etc/profile

#
# clean up X environment
rm -rf /tmp/.X*
mkdir -p "$HOME/.x11vnc"


if [ ! -f $HOME/cron.log ]; then
  touch $HOME/cron.log
fi


#
# start the display environment for iptvboss
/usr/bin/openbox &
$NOVNC_HOME/utils/launch.sh --vnc localhost:$VNC_PORT --listen $PORT &
Xvfb $DISPLAY -screen 0 "$VNC_RESOLUTION"x"$VNC_COL_DEPTH" &
x11vnc -xkb -noxrecord -noxfixes -noxdamage -permitfiletransfer -tightfilexfer -display $DISPLAY -forever -o $HOME/.x11vnc/x11vnc.log -bg && tail -f $HOME/cron.log $HOME/.x11vnc/x11vnc.log
