#!/bin/bash

#
# setup environment
set -xe
source /etc/profile
export HOME="/home/iptvboss"

#
# clean up X environment
rm -rf /tmp/.X*
mkdir -p "$HOME/.x11vnc"

#
# setup iptvboss environment
if [ ! -d $HOME/iptvboss ]; then
  mkdir -p $HOME/iptvboss
  echo 'sceneHeight: 936.0' > $HOME/iptvboss/config.yaml
  echo 'sceneWidth: 1270.0' >> $HOME/iptvboss/config.yaml
fi
wget -qO $HOME/iptvboss/iptvboss.jar "https://www.dropbox.com/s/0v5uil9k6uir7an/IPTVBoss.jar?dl=1"

if [ ! -d $HOME/jdk-15.0.1-full ]; then
  wget -qO- "https://download.bell-sw.com/java/15.0.1+9/bellsoft-jdk15.0.1+9-linux-amd64-full.tar.gz" | tar xz -C $HOME
fi


#
# start the display environment for iptvboss
/usr/bin/openbox &
$NOVNC_HOME/utils/launch.sh --vnc localhost:$VNC_PORT --listen $PORT &
Xvfb $DISPLAY -screen 0 "$VNC_RESOLUTION"x"$VNC_COL_DEPTH" &
cd $HOME/iptvboss;$HOME/jdk-15.0.1-full/bin/java --module-path $HOME/jdk-15.0.1-full/jmods -jar iptvboss.jar > $HOME/iptvboss.log 2>&1
x11vnc -xkb -noxrecord -noxfixes -noxdamage -permitfiletransfer -tightfilexfer -display $DISPLAY -forever -o $HOME/.x11vnc/x11vnc.log && tail -f $HOME/iptvboss.log
