#!/bin/bash

#
# setup environment
set -xe
source /etc/profile
export HOME="/home/iptvboss"

#
# clean up X environment
rm -rf /tmp/.X*
mkdir -p "$HOME/.x11vnc"

#
# setup iptvboss environment
if [ ! -d $HOME/iptvboss ]; then
  mkdir -p $HOME/iptvboss
  echo 'sceneHeight: 936.0' > $HOME/iptvboss/config.yaml
  echo 'sceneWidth: 1270.0' >> $HOME/iptvboss/config.yaml
fi
wget -qO $HOME/iptvboss.jar "https://www.dropbox.com/s/ifw4ke8fvm4cl7v/IPTVBoss.jar?dl=1"

if [ ! -d $HOME/jdk-15.0.1-full ]; then
  wget -qO- "https://download.bell-sw.com/java/15.0.1+9/bellsoft-jdk15.0.1+9-linux-amd64-full.tar.gz" | tar xz -C $HOME
fi

#
# build appinit script
echo "#!/bin/bash" > $HOME/appinit.sh
echo "export LD_LIBRARY_PATH=$HOME/jdk-15.0.1-full/lib" >> $HOME/appinit.sh
echo "export PATH_TO_FX=$HOME/jdk-15.0.1-full/lib" >> $HOME/appinit.sh
echo "export DISPLAY=:0" >> $HOME/appinit.sh
echo "killall java" >> $HOME/appinit.sh
echo "cd $HOME/iptvboss;$HOME/jdk-15.0.1-full/bin/java --module-path $HOME/jdk-15.0.1-full/jmods -jar iptvboss.jar -noGui" >> $HOME/appinit.sh
echo "cd $HOME/iptvboss;$HOME/jdk-15.0.1-full/bin/java --module-path $HOME/jdk-15.0.1-full/jmods -jar iptvboss.jar &" >> $HOME/appinit.sh
chmod +x -v $HOME/appinit.sh

#
# start the display environment for iptvboss
/usr/bin/openbox &
$NOVNC_HOME/utils/launch.sh --vnc localhost:$VNC_PORT --listen $PORT &
Xvfb $DISPLAY -screen 0 "$VNC_RESOLUTION"x"$VNC_COL_DEPTH" &
cd $HOME/iptvboss;$HOME/jdk-15.0.1-full/bin/java --module-path $HOME/jdk-15.0.1-full/jmods -jar iptvboss.jar &
x11vnc -xkb -noxrecord -noxfixes -noxdamage -permitfiletransfer -tightfilexfer -display $DISPLAY -forever -o $HOME/.x11vnc/x11vnc.log -bg && tail -f $HOME/.x11vnc/x11vnc.log
